// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: configuration.proto

package sidelinepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Upstream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Target forge
	//
	// Types that are assignable to Forge:
	//	*Upstream_Git
	Forge isUpstream_Forge `protobuf_oneof:"forge"`
	// Depth we need to clone
	// For tags or branches targeting latest, only 1 is needed for example
	Depth int32 `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	// Target revision
	//
	// Types that are assignable to Target:
	//	*Upstream_Tag
	Target isUpstream_Target `protobuf_oneof:"target"`
}

func (x *Upstream) Reset() {
	*x = Upstream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configuration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Upstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upstream) ProtoMessage() {}

func (x *Upstream) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upstream.ProtoReflect.Descriptor instead.
func (*Upstream) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{0}
}

func (m *Upstream) GetForge() isUpstream_Forge {
	if m != nil {
		return m.Forge
	}
	return nil
}

func (x *Upstream) GetGit() string {
	if x, ok := x.GetForge().(*Upstream_Git); ok {
		return x.Git
	}
	return ""
}

func (x *Upstream) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (m *Upstream) GetTarget() isUpstream_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (x *Upstream) GetTag() string {
	if x, ok := x.GetTarget().(*Upstream_Tag); ok {
		return x.Tag
	}
	return ""
}

type isUpstream_Forge interface {
	isUpstream_Forge()
}

type Upstream_Git struct {
	// A git remote
	Git string `protobuf:"bytes,1,opt,name=git,proto3,oneof"`
}

func (*Upstream_Git) isUpstream_Forge() {}

type isUpstream_Target interface {
	isUpstream_Target()
}

type Upstream_Tag struct {
	// Caller wants a tag
	Tag string `protobuf:"bytes,3,opt,name=tag,proto3,oneof"`
}

func (*Upstream_Tag) isUpstream_Target() {}

type Changes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Paths listed here are recursively copied into Source0
	// and overridden (always choosing upstream)
	RecursivePath []string `protobuf:"bytes,1,rep,name=recursive_path,json=recursivePath,proto3" json:"recursive_path,omitempty"`
}

func (x *Changes) Reset() {
	*x = Changes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configuration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Changes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Changes) ProtoMessage() {}

func (x *Changes) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Changes.ProtoReflect.Descriptor instead.
func (*Changes) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *Changes) GetRecursivePath() []string {
	if x != nil {
		return x.RecursivePath
	}
	return nil
}

type PresetOverride struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Override:
	//	*PresetOverride_BaseUrl
	//	*PresetOverride_FullUrl
	Override isPresetOverride_Override `protobuf_oneof:"override"`
}

func (x *PresetOverride) Reset() {
	*x = PresetOverride{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configuration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresetOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetOverride) ProtoMessage() {}

func (x *PresetOverride) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetOverride.ProtoReflect.Descriptor instead.
func (*PresetOverride) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{2}
}

func (m *PresetOverride) GetOverride() isPresetOverride_Override {
	if m != nil {
		return m.Override
	}
	return nil
}

func (x *PresetOverride) GetBaseUrl() string {
	if x, ok := x.GetOverride().(*PresetOverride_BaseUrl); ok {
		return x.BaseUrl
	}
	return ""
}

func (x *PresetOverride) GetFullUrl() string {
	if x, ok := x.GetOverride().(*PresetOverride_FullUrl); ok {
		return x.FullUrl
	}
	return ""
}

type isPresetOverride_Override interface {
	isPresetOverride_Override()
}

type PresetOverride_BaseUrl struct {
	BaseUrl string `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3,oneof"`
}

type PresetOverride_FullUrl struct {
	FullUrl string `protobuf:"bytes,2,opt,name=full_url,json=fullUrl,proto3,oneof"`
}

func (*PresetOverride_BaseUrl) isPresetOverride_Override() {}

func (*PresetOverride_FullUrl) isPresetOverride_Override() {}

type Configuration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Preset for source package
	// Currently only supports "rocky8" or "manual"
	// "rocky8" sets "base_url" to "https://dl.rockylinux.org/pub/rocky/8"
	// "manual" sets nothing
	Preset string `protobuf:"bytes,1,opt,name=preset,proto3" json:"preset,omitempty"`
	// Source package name
	// SRPM to be fetched from the source repository
	// Format: {repo}//{name}
	// Example: BaseOS//kernel
	Package string `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	// Upstream information
	// Where the upstream of this package is located
	// Only git is supported for now
	Upstream *Upstream `protobuf:"bytes,3,opt,name=upstream,proto3" json:"upstream,omitempty"`
	// Changes we want to pull from upstream
	Changes *Changes `protobuf:"bytes,4,opt,name=changes,proto3" json:"changes,omitempty"`
	// Manual override for preset
	// Only used if preset is "manual"
	PresetOverride *PresetOverride `protobuf:"bytes,5,opt,name=preset_override,json=presetOverride,proto3" json:"preset_override,omitempty"`
	// Whether to add the patch to prep or not
	// Packages that are not auto-patched will need to set this and n_path
	AddToPrep bool `protobuf:"varint,6,opt,name=add_to_prep,json=addToPrep,proto3" json:"add_to_prep,omitempty"`
	// Patch strip depth
	NPath int32 `protobuf:"varint,7,opt,name=n_path,json=nPath,proto3" json:"n_path,omitempty"`
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configuration_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{3}
}

func (x *Configuration) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *Configuration) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Configuration) GetUpstream() *Upstream {
	if x != nil {
		return x.Upstream
	}
	return nil
}

func (x *Configuration) GetChanges() *Changes {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *Configuration) GetPresetOverride() *PresetOverride {
	if x != nil {
		return x.PresetOverride
	}
	return nil
}

func (x *Configuration) GetAddToPrep() bool {
	if x != nil {
		return x.AddToPrep
	}
	return false
}

func (x *Configuration) GetNPath() int32 {
	if x != nil {
		return x.NPath
	}
	return 0
}

var File_configuration_proto protoreflect.FileDescriptor

var file_configuration_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x69, 0x64, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x22,
	0x5b, 0x0a, 0x08, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x03, 0x67,
	0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x67, 0x69, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x64, 0x65, 0x70, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x03, 0x74, 0x61, 0x67, 0x42, 0x07, 0x0a, 0x05, 0x66, 0x6f, 0x72,
	0x67, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x30, 0x0a, 0x07,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x75, 0x72,
	0x73, 0x69, 0x76, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0d, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x56,
	0x0a, 0x0e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65,
	0x12, 0x1b, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x62, 0x61, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a,
	0x08, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x07, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x72, 0x6c, 0x42, 0x0a, 0x0a, 0x08, 0x6f, 0x76,
	0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x22, 0x98, 0x02, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x73,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x73, 0x65, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x75, 0x70,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73,
	0x69, 0x64, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x08, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x2b, 0x0a, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x69,
	0x64, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x52, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x0f, 0x70, 0x72, 0x65, 0x73, 0x65,
	0x74, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x72, 0x65, 0x73,
	0x65, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x52, 0x0e, 0x70, 0x72, 0x65, 0x73,
	0x65, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x61, 0x64,
	0x64, 0x5f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x65, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x61, 0x64, 0x64, 0x54, 0x6f, 0x50, 0x72, 0x65, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x50, 0x61, 0x74,
	0x68, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x72, 0x6f, 0x63, 0x6b, 0x79, 0x2d, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2f, 0x73, 0x69, 0x64, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x2f, 0x70, 0x62, 0x3b, 0x73, 0x69, 0x64, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_configuration_proto_rawDescOnce sync.Once
	file_configuration_proto_rawDescData = file_configuration_proto_rawDesc
)

func file_configuration_proto_rawDescGZIP() []byte {
	file_configuration_proto_rawDescOnce.Do(func() {
		file_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(file_configuration_proto_rawDescData)
	})
	return file_configuration_proto_rawDescData
}

var file_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_configuration_proto_goTypes = []interface{}{
	(*Upstream)(nil),       // 0: sideline.Upstream
	(*Changes)(nil),        // 1: sideline.Changes
	(*PresetOverride)(nil), // 2: sideline.PresetOverride
	(*Configuration)(nil),  // 3: sideline.Configuration
}
var file_configuration_proto_depIdxs = []int32{
	0, // 0: sideline.Configuration.upstream:type_name -> sideline.Upstream
	1, // 1: sideline.Configuration.changes:type_name -> sideline.Changes
	2, // 2: sideline.Configuration.preset_override:type_name -> sideline.PresetOverride
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_configuration_proto_init() }
func file_configuration_proto_init() {
	if File_configuration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_configuration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Upstream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configuration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Changes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configuration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresetOverride); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configuration_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configuration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_configuration_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Upstream_Git)(nil),
		(*Upstream_Tag)(nil),
	}
	file_configuration_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*PresetOverride_BaseUrl)(nil),
		(*PresetOverride_FullUrl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_configuration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configuration_proto_goTypes,
		DependencyIndexes: file_configuration_proto_depIdxs,
		MessageInfos:      file_configuration_proto_msgTypes,
	}.Build()
	File_configuration_proto = out.File
	file_configuration_proto_rawDesc = nil
	file_configuration_proto_goTypes = nil
	file_configuration_proto_depIdxs = nil
}
